name: Deploy docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependenct-path: '**/package-lock.json'

      - run: npm ci

      - run: npm run build
        env: 
          TURBO_TOKEN: sZOGaLHGd4T9oboekV8oKnu1
          TURBO_TEAM: run-to-the-woods

      - name: Deploy storybook
        working-directory: './packages/docs'
        run: npm run deploy-storybook -- --ci --existing-output-dir=dist
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}


